site_name: IdontKnowRoot
site_url: https://root.dianas.cyou/
site_description: 刷机指南
site_author: IdontKnowRoot Team
repo_url: https://github.com/sudoskys/Root
edit_uri: edit/main/docs/
copyright: >
        Copyright &copy; GFDL 协议
        <a href="#__consent">Change cookie settings</a>

nav:
    - 前言: index.md
    - 准备: 
          - 起始: prepare/index.md
          - 术语: prepare/term.md
          - 解锁Bootloader: prepare/bootloader.md
    - 刷机:
          - 起始: Root/index.md
          - 线刷: Root/Wirebrush.md
          - 卡刷: Root/Brushcard.md
          - 深刷: Root/Deep.md
          - GSI: Root/Gsi.md
          - 救砖: Root/Savebrick.md
          - Huawei: Root/Huawei.md
    - 优化: optimize.md
    - 模块: module.md
    - 内核: kernel.md
    - 关于: about.md

theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    logo: material/navigation
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections


markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.superfences
  - meta
  - pymdownx.tabbed:
      alternate_style: true
    

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/gjzsr
  analytics:
    provider: custom
    property: foobar
  consent:
    title: Cookie 请求
    description: >- 
      我们使用Cloudflare分析服务收集有关我们的网站用户的地理位置以及他们访问的页面的信息。
      这样做是为了监测和改进站点配置，以便我们为用户对站点的需求提供最好的支持。同样的信息也用于组织内部以支持战略决策。 
      当您第一次访问我们的网站时，系统会询问您是否接受cookies以获得完整的网站体验。如果您接受，这将成为我们在您下次访问时存储在cookie中的信息之一。 
      Cookies以匿名形式收集信息。若要管理第三方cookie，您可以更改cookie设置。 
    cookies:
      https://root.dianas.cyou/:
        name: Cloudflare Analytics
        checked: true


plugins:
  - glightbox
  - search
  - social:
      cards_font: Noto Sans SC
      cards_color:
        fill: '#000026'
        text: '#FF770F'
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true